//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pegasus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AITISIS_ORIGINAL
    {
        public int AITISI_ID { get; set; }
        public Nullable<System.DateTime> AITISI_DATE { get; set; }
        public string AITISI_PROTOCOL { get; set; }
        public Nullable<int> PROKIRIXI_ID { get; set; }
        public string AFM { get; set; }
        public Nullable<int> AGE { get; set; }
        public Nullable<int> CHILDREN { get; set; }
        public Nullable<int> ANERGIA { get; set; }
        public Nullable<int> ANERGIA_OLD { get; set; }
        public Nullable<int> SOCIALGROUP { get; set; }
        public string SOCIALGROUP_PROTOCOL { get; set; }
        public string SOCIALGROUP_YPIRESIA { get; set; }
        public Nullable<bool> SOCIALGROUP1 { get; set; }
        public Nullable<bool> SOCIALGROUP2 { get; set; }
        public Nullable<bool> SOCIALGROUP3 { get; set; }
        public Nullable<bool> SOCIALGROUP4 { get; set; }
        public string SOCIALGROUP1_DOC { get; set; }
        public string SOCIALGROUP2_DOC { get; set; }
        public string SOCIALGROUP3_DOC { get; set; }
        public string SOCIALGROUP4_DOC { get; set; }
        public Nullable<int> N2190 { get; set; }
        public Nullable<bool> CERTIFIED { get; set; }
        public Nullable<int> KLADOS { get; set; }
        public Nullable<int> EIDIKOTITA { get; set; }
        public Nullable<int> EIDIKOTITA_GROUP { get; set; }
        public Nullable<int> BASIC_EDUCATION { get; set; }
        public string PTYXIO_TITLOS { get; set; }
        public Nullable<decimal> PTYXIO_BATHMOS { get; set; }
        public Nullable<System.DateTime> PTYXIO_DATE { get; set; }
        public Nullable<bool> MSC { get; set; }
        public string MSC_TITLOS { get; set; }
        public Nullable<int> MSC_DIARKEIA { get; set; }
        public Nullable<bool> PHD { get; set; }
        public string PHD_TITLOS { get; set; }
        public Nullable<bool> PED { get; set; }
        public string PED_TITLOS { get; set; }
        public Nullable<int> PED_DIARKEIA { get; set; }
        public Nullable<bool> AED_MSC { get; set; }
        public string AED_MSC_TITLOS { get; set; }
        public Nullable<bool> AED_PHD { get; set; }
        public string AED_PHD_TITLOS { get; set; }
        public string LANG_TEXT { get; set; }
        public string LANG_LEVEL { get; set; }
        public string LANG_TITLOS { get; set; }
        public string LANG1_TEXT { get; set; }
        public string LANG1_LEVEL { get; set; }
        public string LANG1_TITLOS { get; set; }
        public string LANG2_TEXT { get; set; }
        public string LANG2_LEVEL { get; set; }
        public string LANG2_TITLOS { get; set; }
        public Nullable<int> COMPUTER_CERT { get; set; }
        public string COMPUTER_TITLOS { get; set; }
        public Nullable<bool> EPIMORFOSI1 { get; set; }
        public Nullable<int> EPIMORFOSI1_HOURS { get; set; }
        public Nullable<bool> EPIMORFOSI2 { get; set; }
        public Nullable<int> EPIMORFOSI2_HOURS { get; set; }
        public Nullable<bool> EPIMORFOSI3 { get; set; }
        public Nullable<int> EPIMORFOSI3_HOURS { get; set; }
        public Nullable<int> PERIFERIA_ID { get; set; }
        public Nullable<int> SCHOOL_ID { get; set; }
        public Nullable<int> EPAGELMA_STATUS { get; set; }
        public Nullable<float> MORIA_ANERGIA { get; set; }
        public Nullable<float> MORIA_SOCIAL { get; set; }
        public Nullable<float> MORIA_PTYXIO { get; set; }
        public Nullable<float> MORIA_MSC { get; set; }
        public Nullable<float> MORIA_PHD { get; set; }
        public Nullable<float> MORIA_PED { get; set; }
        public Nullable<float> MORIA_AED_MSC { get; set; }
        public Nullable<float> MORIA_AED_PHD { get; set; }
        public Nullable<float> MORIA_LANG { get; set; }
        public Nullable<float> MORIA_COMPUTER { get; set; }
        public Nullable<float> MORIA_EPIMORFOSI1 { get; set; }
        public Nullable<float> MORIA_EPIMORFOSI2 { get; set; }
        public Nullable<float> MORIA_EPIMORFOSI3 { get; set; }
        public Nullable<float> MORIA_TEACH { get; set; }
        public Nullable<float> MORIA_WORK1 { get; set; }
        public Nullable<float> MORIA_WORK2 { get; set; }
        public Nullable<float> MORIA_WORK { get; set; }
        public Nullable<float> MORIA_TOTAL { get; set; }
        public Nullable<System.DateTime> TIMESTAMP { get; set; }
        public Nullable<int> PTYXIO_TYPE { get; set; }
    
        public virtual TEACHERS TEACHERS { get; set; }
    }
}
