//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pegasus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROKIRIXIS
    {
        public PROKIRIXIS()
        {
            this.PROKIRIXIS_EIDIKOTITES = new HashSet<PROKIRIXIS_EIDIKOTITES>();
            this.PROKIRIXIS_SCHOOLS = new HashSet<PROKIRIXIS_SCHOOLS>();
            this.AITISIS = new HashSet<AITISIS>();
            this.AITISIS1 = new HashSet<AITISIS>();
        }
    
        public int ID { get; set; }
        public string PROTOCOL { get; set; }
        public string FEK { get; set; }
        public string FOREAS { get; set; }
        public Nullable<int> SCHOOL_YEAR { get; set; }
        public Nullable<System.DateTime> DATE_START { get; set; }
        public Nullable<System.DateTime> DATE_END { get; set; }
        public string DIOIKITIS { get; set; }
        public Nullable<short> STATUS { get; set; }
        public Nullable<bool> ACTIVE { get; set; }
        public Nullable<bool> USER_VIEW { get; set; }
        public Nullable<bool> ADMIN { get; set; }
        public Nullable<bool> ENSTASEIS { get; set; }
        public string HOUR_START { get; set; }
        public string HOUR_END { get; set; }
    
        public virtual ICollection<PROKIRIXIS_EIDIKOTITES> PROKIRIXIS_EIDIKOTITES { get; set; }
        public virtual ICollection<PROKIRIXIS_SCHOOLS> PROKIRIXIS_SCHOOLS { get; set; }
        public virtual ICollection<AITISIS> AITISIS { get; set; }
        public virtual ICollection<AITISIS> AITISIS1 { get; set; }
    }
}
