//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pegasus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class REEDUCATION
    {
        public int EDUCATION_ID { get; set; }
        public Nullable<int> AITISI_ID { get; set; }
        public Nullable<int> PROKIRIXI_ID { get; set; }
        public string AFM { get; set; }
        public Nullable<System.DateTime> CERTIFICATE_DATE { get; set; }
        public string CERTIFICATE_FOREAS { get; set; }
        public string CERTIFICATE_TITLE { get; set; }
        public Nullable<int> CERTIFICATE_HOURS { get; set; }
    }
}
