//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pegasus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class sqlAITISEIS_WITHOUT_EXPERIENCE
    {
        public int AITISI_ID { get; set; }
        public Nullable<int> PROKIRIXI_ID { get; set; }
        public string PROTOCOL { get; set; }
        public string AITISI_PROTOCOL { get; set; }
        public string AFM { get; set; }
        public string FULLNAME { get; set; }
        public string SCHOOL_NAME { get; set; }
        public int SCHOOL_ID { get; set; }
        public string EIDIKOTITA_DESC { get; set; }
        public string KLADOS_NAME { get; set; }
        public Nullable<int> EIDIKOTITA_KLADOS_ID { get; set; }
        public Nullable<int> AGE { get; set; }
        public Nullable<int> SCHOOL_YEAR { get; set; }
        public int EIDIKOTITA_ID { get; set; }
    }
}
