//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pegasus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class sqlEXP_TEACHING_2_OLD
    {
        public int AITISI_ID { get; set; }
        public string KLADOS_NAME { get; set; }
        public string TYPE_TEXT { get; set; }
        public Nullable<int> TEACH_TYPE { get; set; }
        public Nullable<int> KLADOS { get; set; }
        public Nullable<double> MORIA_TOTAL { get; set; }
    }
}
