//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pegasus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class sqlEIDIKOTITES_IN_SCHOOLS
    {
        public int PSE_ID { get; set; }
        public int PROKIRIXI_ID { get; set; }
        public int SCHOOL_ID { get; set; }
        public int EIDIKOTITA_ID { get; set; }
        public string SCHOOL_NAME { get; set; }
        public string PERIFERIA_NAME { get; set; }
        public string PERIFERIAKI { get; set; }
    }
}
