//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pegasus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class sqlTEACHERS_IN_AITISEIS
    {
        public string AFM { get; set; }
        public string FULLNAME { get; set; }
        public string TELEPHONE { get; set; }
        public string MOBILE { get; set; }
        public string EMAIL { get; set; }
        public Nullable<int> AGE { get; set; }
        public Nullable<int> CHILDREN { get; set; }
        public string EIDIKOTITA_TEXT { get; set; }
        public string SCHOOL_NAME { get; set; }
        public Nullable<int> SCHOOL_ID { get; set; }
        public int EIDIKOTITA_ID { get; set; }
        public Nullable<int> PROKIRIXI_ID { get; set; }
        public int AITISI_ID { get; set; }
        public string AITISI_PROTOCOL { get; set; }
        public Nullable<int> SCHOOL_PERIFERIAKI_ID { get; set; }
    }
}
