//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pegasus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class sqlTEACHER_ACCOUNTS_INFO
    {
        public int USER_ID { get; set; }
        public string USERNAME { get; set; }
        public string FULLNAME { get; set; }
        public string FATHERNAME { get; set; }
        public string MOTHERNAME { get; set; }
        public Nullable<System.DateTime> BIRTHDATE { get; set; }
        public string AMKA { get; set; }
        public string TELEPHONES { get; set; }
        public string AFM { get; set; }
    }
}
