//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pegasus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class sqlTEACHERS_WITH_AITISEIS_UNIQUE
    {
        public string AFM { get; set; }
        public string FULLNAME { get; set; }
        public string TELEPHONE { get; set; }
        public string MOBILE { get; set; }
        public string EMAIL { get; set; }
        public string FULLADDRESS { get; set; }
    }
}
