//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pegasus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class sqlTEACHER_AITISEIS
    {
        public string AITISI_PROTOCOL { get; set; }
        public string PERIFERIA_NAME { get; set; }
        public string AFM { get; set; }
        public string FULLNAME { get; set; }
        public string EIDIKOTITA_TEXT { get; set; }
        public Nullable<int> PROKIRIXI_ID { get; set; }
        public int AITISI_ID { get; set; }
        public Nullable<int> PERIFERIA_ID { get; set; }
        public Nullable<int> SCHOOL_ID { get; set; }
        public string SCHOOL_NAME { get; set; }
        public Nullable<bool> CHECK_STATUS { get; set; }
        public Nullable<bool> ENSTASI { get; set; }
        public string PROTOCOL { get; set; }
        public Nullable<System.DateTime> DATE_START { get; set; }
        public int PERIFERIAKI_ID { get; set; }
        public string PERIFERIAKI { get; set; }
    }
}
