//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pegasus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class sqlTEACHERS_WITH_AITISEIS
    {
        public string AFM { get; set; }
        public string FULLNAME { get; set; }
        public string TELEPHONE { get; set; }
        public string MOBILE { get; set; }
        public string EMAIL { get; set; }
        public string EIDIKOTITA_TEXT { get; set; }
        public Nullable<int> EIDIKOTITA { get; set; }
        public string AMKA { get; set; }
        public Nullable<int> EIDIKOTITA_KLADOS_ID { get; set; }
        public int SCHOOL_ID { get; set; }
        public string SCHOOL_NAME { get; set; }
    }
}
