//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pegasus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_PERIFERIES
    {
        public SYS_PERIFERIES()
        {
            this.SYS_DIMOS = new HashSet<SYS_DIMOS>();
            this.SYS_SCHOOLS = new HashSet<SYS_SCHOOLS>();
            this.TEACHERS = new HashSet<TEACHERS>();
        }
    
        public int PERIFERIA_ID { get; set; }
        public string PERIFERIA_NAME { get; set; }
    
        public virtual ICollection<SYS_DIMOS> SYS_DIMOS { get; set; }
        public virtual ICollection<SYS_SCHOOLS> SYS_SCHOOLS { get; set; }
        public virtual ICollection<TEACHERS> TEACHERS { get; set; }
    }
}
