//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pegasus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_SCHOOLS
    {
        public int SCHOOL_ID { get; set; }
        public string SCHOOL_NAME { get; set; }
        public string SCHOOL_EMAIL { get; set; }
        public Nullable<int> SCHOOL_TYPEID { get; set; }
        public Nullable<int> SCHOOL_PERIFERIA_ID { get; set; }
        public Nullable<int> SCHOOL_PERIFERIAKI_ID { get; set; }
    
        public virtual SYS_PERIFERIAKES SYS_PERIFERIAKES { get; set; }
        public virtual SYS_PERIFERIES SYS_PERIFERIES { get; set; }
    }
}
