//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pegasus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_SPOUDES_TYPES
    {
        public int SPOUDES_TYPE_ID { get; set; }
        public string SPOUDES_TYPE { get; set; }
        public Nullable<int> SPOUDES_KLADOS_ID { get; set; }
    
        public virtual SYS_KLADOS SYS_KLADOS { get; set; }
    }
}
