//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pegasus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_TEACH2_TYPES
    {
        public int TYPE_ID { get; set; }
        public string TYPE_TEXT { get; set; }
        public Nullable<float> TYPE_MORIA { get; set; }
        public Nullable<float> TYPE_MORIA_MAX { get; set; }
        public string TYPE_DESCRIPTION { get; set; }
    }
}
