//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pegasus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_TAXFREE
    {
        public int YEAR_ID { get; set; }
        public string YEAR_TEXT { get; set; }
        public Nullable<float> TAXFREE { get; set; }
        public string NOMISMA { get; set; }
    }
}
