//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pegasus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_ANERGIA_OLD
    {
        public int ANERGIA_ID { get; set; }
        public string ANERGIA_TAG { get; set; }
        public Nullable<float> ANERGIA_MORIA { get; set; }
    }
}
