//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pegasus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_PERIFERIAKES
    {
        public SYS_PERIFERIAKES()
        {
            this.SYS_SCHOOLS = new HashSet<SYS_SCHOOLS>();
        }
    
        public int PERIFERIAKI_ID { get; set; }
        public string PERIFERIAKI { get; set; }
    
        public virtual ICollection<SYS_SCHOOLS> SYS_SCHOOLS { get; set; }
    }
}
