//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pegasus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_SOCIALGROUPS
    {
        public int CATEGORY_ID { get; set; }
        public string CATEGORY { get; set; }
        public Nullable<float> CATEGORY_MORIA { get; set; }
    }
}
