//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pegasus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_SCHOOLYEARS
    {
        public int SY_ID { get; set; }
        public string SY_TEXT { get; set; }
        public Nullable<System.DateTime> SY_DATESTART { get; set; }
        public Nullable<System.DateTime> SY_DATEEND { get; set; }
    }
}
