//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pegasus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_KLADOS
    {
        public SYS_KLADOS()
        {
            this.SYS_EIDIKOTITES = new HashSet<SYS_EIDIKOTITES>();
            this.SYS_SPOUDES_TYPES = new HashSet<SYS_SPOUDES_TYPES>();
        }
    
        public int KLADOS_ID { get; set; }
        public string KLADOS_NAME { get; set; }
        public string KLADOS_CATEGORY { get; set; }
    
        public virtual ICollection<SYS_EIDIKOTITES> SYS_EIDIKOTITES { get; set; }
        public virtual ICollection<SYS_SPOUDES_TYPES> SYS_SPOUDES_TYPES { get; set; }
    }
}
