//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pegasus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEACHERS
    {
        public TEACHERS()
        {
            this.AITISIS = new HashSet<AITISIS>();
            this.AITISIS_ORIGINAL = new HashSet<AITISIS_ORIGINAL>();
        }
    
        public string AFM { get; set; }
        public string ADT { get; set; }
        public string AMKA { get; set; }
        public string FIRSTNAME { get; set; }
        public string LASTNAME { get; set; }
        public string FATHERNAME { get; set; }
        public string MOTHERNAME { get; set; }
        public Nullable<int> GENDER { get; set; }
        public Nullable<System.DateTime> BIRTHDATE { get; set; }
        public string MARITAL_STATUS { get; set; }
        public Nullable<int> ARMY_STATUS { get; set; }
        public string TELEPHONE { get; set; }
        public string MOBILE { get; set; }
        public string EMAIL { get; set; }
        public string ADDRESS { get; set; }
        public string CITY { get; set; }
        public string TK { get; set; }
        public string DIMOS { get; set; }
        public string COMMENT { get; set; }
        public string DOY { get; set; }
        public Nullable<int> PERIFERIA { get; set; }
    
        public virtual SYS_PERIFERIES SYS_PERIFERIES { get; set; }
        public virtual ICollection<AITISIS> AITISIS { get; set; }
        public virtual ICollection<AITISIS_ORIGINAL> AITISIS_ORIGINAL { get; set; }
    }
}
