//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pegasus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class xUploadedVocationFiles
    {
        public int FileID { get; set; }
        public string FileName { get; set; }
        public string Category { get; set; }
        public Nullable<int> ProkirixiID { get; set; }
        public Nullable<int> AitisiID { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public string UploadSummary { get; set; }
        public string TeacherAFM { get; set; }
    }
}
